#!/bin/bash -e
if [[ ! -f /bin/which ]]; then
    which () {
        whereis $1 | sed "s/$1://"
    }
else
    which () {
        /bin/which $1
    }
fi

if [[ -n $(which apt-get) ]]; then
    installer="sudo apt-get install"
elif [[ -n $(which brew) ]]; then
    installer="brew install"
else
    echo 'Cannot find installer `apt-get` or `brew`'
    echo 'If components are missing, I may not be able to install them'
fi

if [[ -z $(which wget) ]]; then
    if [[ -z $(which curl) ]]; then
        $installer wget
        downloader=wget
        header="wget -S -qO-"
    else
        downloader="curl -O"
        header="curl -IL"
    fi
else
    header="wget -S -qO-"
    downloader=wget
fi

# MySQL handling
sudo service mysql start || true

if [ -z "$1" ]; then
    read -p "Specify subdomain name: " domain
else
    domain=$1
fi

if [ -z "$2" ]; then
    read -p "Specify the drupal version to install (7.26): " druverzh
else
    $druverzh=$2
fi
druverzh=${druverzh:-"7.26"}

if [ -z "$3" ]; then
    read -p "Specify the document root: " docroot
else
    docroot=$3
fi
mkdir -p $docroot

# FIXME update to handle arguments better
# Allow setting of drupal version, target, and subdomain
$downloader http://ftp.drupal.org/files/projects/drupal-${druverzh}.tar.gz
tar --extract --gzip --file drupal-${druverzh}.tar.gz

cp -r drupal-${druverzh}/* $docroot
rm -rf drupal-${druverzh}*

sudo ./mksubdomain $domain $docroot
sudo service apache2 restart
# wget outputs headers to stderr
if [[ -n $($header http://${domain}.localhost 2>&1 | \grep "200 OK") ]]; then
    echo "Website appears to be up and running."
    echo "You should be all set."
    google-chrome http://${domain}.localhost/install.php
else
    echo "Website is not returning 200 for index page.  Ack!"
fi
