#!/bin/bash -e
# Create a subdomain for apache
# Must be run with `sudo`
echo "127.0.0.1	${1}.localhost" >> /etc/hosts
echo "<VirtualHost *:80>
    DocumentRoot $(pwd)/$1
    ServerName ${1}.localhost
    <Directory "$(pwd)/$1">
        AllowOverride all
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>" > /etc/apache2/sites-available/${1}.conf
cd /etc/apache2/sites-enabled
ln -s ../sites-available/${1}.conf ${1}.conf
