#!/bin/bash -e
sudo echo "127.0.0.1	${1}.localhost" >> /etc/hosts
sudo echo "<VirtualHost *:80>
    DocumentRoot $(pwd)
    ServerName ${1}.localhost
    <Directory "$(pwd)">
        AllowOverride all
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>" > /etc/apache2/sites-available/${1}.conf
cd /etc/apache2/sites-enabled
sudo ln -s ../sites-available/${1}.conf ${1}.conf
